import { spellSizeIcon } from '@/components/app-shell/spell-icons';
import { PrimaryMetricsPanel } from '@/components/app-shell/PrimaryMetricsPanel';
import { displayFuryStage } from '@/components/ui/fury-display';
import { appFonts, dragonTheme } from '@/constants/dragon-theme';
import { WORLD_CONSTANTS } from '@/constants/world.constants';
import { calculateAverageCrimsonHeartCharge, calculateFuryChange } from '@/data/calculations/formula-resources';
import { calculateProgressionPreview } from '@/data/calculations/progression-preview';
import { milestoneForEnergy, milestoneLabel } from '@/data/world-data/milestones';
import { SPELL_SIZES } from '@/data/world-data/spells';
import { useOfflineProgressStore } from '@/store/store-offline-progress/_useOfflineProgressStore';
import { useOnlineProgressStore } from '@/store/store-online-progress/_useOnlineProgressStore';
import { useProductionSpecialStore } from '@/store/store-production-special/_useProductionSpecialStore';
import { useProductivityStore } from '@/store/store-productivity/_useProductivityStore';
import { useAppStore } from '@/store/useAppStore';
import { useWorldStore } from '@/store/store-world/_useWorldStore';
import type { AppActivity } from '@/types/world.types';
import { formatDecimal } from '@/utils/decimal';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useShallow } from 'zustand/react/shallow';

export type PanelMode = 'world' | 'population' | 'goals' | 'resources' | 'spells';

const { colors, space } = dragonTheme;

type ResourcePanelId = 'energy' | 'darkEnergy' | 'plasma' | 'darkPlasma' | 'anomaly' | 'chaosEnergy' | 'shards' | 'quarks';
type PanelEntry = { id: string; label: string; value?: string; icon: string; color: string; description: string };

const RESOURCE_TILES: readonly PanelEntry[] = [
	{ id: 'energy', label: 'Energy', icon: '⚡', color: colors.gold, description: 'The core production resource. Producers, amplifiers, and most clicker upgrades turn Energy into deeper progression.' },
	{ id: 'darkEnergy', label: 'Dark Energy', icon: '◈', color: colors.violet, description: 'Harvested from completed goals and generated by dark systems. Spend it on Energy Upgrades and advanced production.' },
	{ id: 'plasma', label: 'Plasma', icon: '◉', color: colors.crimsonBright, description: 'Earned by sacrificing a developed Energy run through Armageddon. Plasma powers prestige upgrades, monuments, and deities.' },
	{ id: 'darkPlasma', label: 'Dark Plasma', icon: '◌', color: colors.violet, description: 'A permanent Transcension currency used for the deepest production, monument, and prestige upgrades.' },
	{ id: 'anomaly', label: 'Anomaly', icon: '⌁', color: colors.blue, description: 'A persistent deep-progression currency earned through Transcension and spent on Titans, Deities, Forges, and respec powers.' },
	{ id: 'chaosEnergy', label: 'Chaos Energy', icon: '✦', color: colors.crimsonBright, description: 'Primordial energy produced through Titan systems. It strengthens several late-game multipliers and growth effects.' },
	{ id: 'quarks', label: 'Quarks', icon: '◇', color: colors.blue, description: 'Quarks fuel high-tier evolution, monument, and Convertor systems.' },
];

const FURY_RATES: Record<AppActivity, number> = {
	pomodoro: -1 / 60,
	'pomodoro-break': -0.5 / 60,
	'off-app': 0.5 / 3600,
	'allowed-app': 1 / 3600,
	idle: 1 / 3600,
	'blocked-app': 5 / 3600,
};
const activityLabel = (activity: AppActivity) => activity.replaceAll('-', ' ');
const durationLabel = (seconds: number) => `${(seconds / 3600).toFixed(1)}h`;
const PANEL_COPY: Record<PanelMode, { title: string; hint: string }> = {
	world: { title: 'World Panel', hint: 'Milestone, Fury, streaks, and current world state' },
	population: { title: 'Population Panel', hint: 'Population growth, losses, and active threats' },
	goals: { title: 'Goals Panel', hint: 'Active work and daily survey streaks' },
	resources: { title: 'Production Panel', hint: 'Currencies and live Energy output' },
	spells: { title: 'Spell Panel', hint: 'Backpack inventory by spell size' },
};

export function SecondaryPanel({ mode }: { mode: PanelMode }) {
	const { resources, totalAllTime, deaths, dragon, hostiles, angerShields, getFuryBand } = useWorldStore(useShallow(state => ({ resources: state.resourceStore.resources, totalAllTime: state.resourceStore.totalAllTime, deaths: state.resourceStore.populationDead, dragon: state.resourceStore.dragon, hostiles: state.populationStore, angerShields: state.dragonStore.angerShields, getFuryBand: state.dragonStore.getFuryBand })));
	const goals = useProductivityStore(state => state.goals);
	const surveys = useProductivityStore(state => state.surveys);
	const pomodoro = useProductivityStore(state => state.pomodoro);
	const spells = useProductionSpecialStore(state => state.spells.spellInventory);
	const heart = useProductionSpecialStore(useShallow(state => ({ charge: state.crimsonHeart.charge, getTargetCharge: state.crimsonHeart.getTargetCharge, getChargeRate: state.crimsonHeart.getChargeRate })));
	const offline = useOfflineProgressStore(useShallow(state => ({ offAppSeconds: state.offAppSeconds, allowedAppSeconds: state.allowedAppSeconds, blockedAppSeconds: state.blockedAppSeconds })));
	const panelLayout = useAppStore(state => state.secondaryPanelLayout);
	const gameMode = useWorldStore(state => state.optionsStore.gameMode);
	const configuredActivity = useWorldStore(state => state.optionsStore.activity);
	const furyBand = getFuryBand();
	const furyStage = displayFuryStage(furyBand, angerShields);
	const milestone = milestoneForEnergy(totalAllTime.energy);
	const activity: AppActivity = pomodoro.status === 'countdown-active' || pomodoro.status === 'count-up' ? 'pomodoro' : pomodoro.status === 'countdown-break' ? 'pomodoro-break' : configuredActivity;
	const activeGoalPressure = Math.max(0, goals.incompleteHabits.length - 10) + Math.max(0, goals.incompleteTasks.length - 10);
	const averageHeart = mode === 'world' ? calculateAverageCrimsonHeartCharge(heart.charge, heart.getTargetCharge(activity), 3_600, heart.getChargeRate()) : 0;
	const estimatedFuryPerHour = mode === 'world' ? calculateFuryChange(FURY_RATES[activity], WORLD_CONSTANTS.gameModes.furyMultiplier[gameMode], 3_600, activeGoalPressure, 1).times(Math.max(1, averageHeart)) : undefined;
	const progression = mode === 'population' ? calculateProgressionPreview(heart.charge) : undefined;
	const pendingGoals = mode === 'world' ? [...goals.completed, ...goals.specialHabits.filter(goal => goal.status === 'completed')].filter(goal => goals.pendingHarvestIds.includes(goal.id)) : [];
	const offlineSeconds = offline.offAppSeconds + offline.allowedAppSeconds + offline.blockedAppSeconds;
	const [selectedId, setSelectedId] = useState<string>();
	const panelCopy = PANEL_COPY[mode];

	if (mode === 'resources') {
		const online = useOnlineProgressStore.getState();
		const baseProduction = online.calculateProducerEnergy(1, 1, 'idle');
		const amplification = online.calculateAmplification();
		const energyPerSecond = baseProduction.times(amplification).times(online.calculateOtherEnergyMultipliers());
		const visibleTiles = RESOURCE_TILES.filter(tile => totalAllTime[tile.id as ResourcePanelId].gt(0));
		const selectedTile = visibleTiles.find(tile => tile.id === selectedId);
		return (
			<View style={styles.panel}>
				<PanelHeading title={panelCopy.title} hint={panelCopy.hint} />
				<View style={styles.resourceGrid}>
					{visibleTiles.map(tile => (
						<PanelItem
							key={tile.id}
							entry={{ ...tile, value: `${formatDecimal(resources[tile.id as ResourcePanelId])}${tile.id === 'energy' ? ` · ${formatDecimal(energyPerSecond)} /s` : ''}` }}
							vertical={panelLayout === 'vertical'}
							selected={selectedId === tile.id}
							onPress={() => setSelectedId(current => current === tile.id ? undefined : tile.id)}
						/>
					))}
				</View>
				{selectedTile ? <PanelDescription entry={selectedTile} /> : null}
				<PrimaryMetricsPanel />
			</View>
		);
	}

	const entries = mode === 'goals' ?
		[
			{ id: 'habits', label: 'Habits', value: `${goals.incompleteHabits.length}`, icon: '✓', color: colors.gold, description: 'Repeatable goals that build a streak when completed on their schedule.' },
			{ id: 'tasks', label: 'Tasks', value: `${goals.incompleteTasks.length}`, icon: '▤', color: colors.blue, description: 'One-time goals that can be completed and harvested for progression rewards.' },
			{ id: 'special', label: 'Dragon Rituals', value: `${goals.specialHabits.filter(goal => goal.status === 'incomplete').length}`, icon: '✦', color: colors.crimsonBright, description: 'Permanent survey and Pomodoro goals. They are checked off automatically by their linked activity.' },
			{ id: 'check-in-streak', label: 'Check-In streak', value: `${surveys.checkInStreak}`, icon: '✓', color: colors.gold, description: 'Consecutive daily check-in cycles completed.' },
			{ id: 'check-out-streak', label: 'Check-Out streak', value: `${surveys.checkOutStreak}`, icon: '⟲', color: colors.violet, description: 'Consecutive daily check-out cycles completed.' },
		]
	: mode === 'spells' ?
		[
			{ id: 'backpack', label: 'Backpack', value: `${spells.length}`, icon: '✧', color: colors.gold, description: 'Your current spell inventory. Open the backpack in the Effects panel to inspect or activate spells.' },
			...SPELL_SIZES.map(size => ({ id: `spell-${size.size}`, label: size.name, value: `${spells.filter(spell => spell.size === size.size).length}`, icon: spellSizeIcon(size.size), color: colors.violet, description: `${size.name} spells have a ×${size.multiplier} base effect and can be combined through the Convertor when their recipe allows it.` })),
		]
	: mode === 'population' ?
		[
			{ id: 'population', label: 'Population', value: formatDecimal(resources.population), icon: '◎', color: colors.blue, description: 'The living population of Earth. Population growth stops during blocked activity, Lock-In, dragon death, or a paused world state.' },
			{ id: 'population-growth', label: 'Growth', value: `+${formatDecimal(progression!.populationPerTick)} / tick`, icon: '↗', color: colors.green, description: `Current Population gained per Heart tick: ${formatDecimal(progression!.populationPerTick)}. Heart ticks are ${formatDecimal(progression!.heartTicksPerSecond, 3)} per second; Angry and Critical Fury can stop growth or cause population loss.` },
			{ id: 'threats', label: 'Threats', value: `${formatDecimal(hostiles.zombies)} · ${formatDecimal(hostiles.cyborgs)}`, icon: '☣', color: colors.crimsonBright, description: 'Zombies and cyborgs are population threats. Their growth and effects change with Fury stages and world modifiers.' },
			{ id: 'deaths', label: 'Deaths', value: formatDecimal(deaths), icon: '†', color: colors.muted, description: 'The total population lost to threats and Fury effects during this run.' },
		]
	: [
			{ id: 'milestone', label: 'Milestone', value: milestoneLabel(milestone), icon: '◆', color: colors.gold, description: 'Milestones are based on all-time Energy and unlock new chambers, systems, and rewards.' },
			{ id: 'fury', label: 'Fury Trend', value: `${estimatedFuryPerHour!.gte(0) ? '+' : ''}${formatDecimal(estimatedFuryPerHour!)} / hr`, icon: '🔥', color: colors.crimsonBright, description: `The dragon is currently ${furyStage}. This estimate is for ${activityLabel(activity)} and includes Heart speed, game mode, active-goal pressure, and shields. The exact Fury total is in the compact row below.` },
			{ id: 'streak', label: 'Streak', value: `${surveys.checkInStreak} · ${surveys.checkOutStreak}`, icon: '⟲', color: colors.gold, description: `Survey streaks: ${surveys.checkInStreak} check-in and ${surveys.checkOutStreak} check-out. Complete the daily survey cycle to keep both streaks moving.` },
			{ id: 'important', label: 'World Status', value: `${dragon.ageDays.toFixed(1)}d · ${durationLabel(offlineSeconds)}`, icon: 'ⓘ', color: colors.violet, description: `Current activity: ${activityLabel(activity)}. Stored offline time: ${durationLabel(offlineSeconds)}. ${pendingGoals.length} completed goal${pendingGoals.length === 1 ? '' : 's'} waiting to be harvested.` },
	];
	const selectedEntry = entries.find(entry => entry.id === selectedId);

	return (
		<View style={styles.panel}>
			<PanelHeading title={panelCopy.title} hint={panelCopy.hint} />
			<View style={[styles.entryContent, panelLayout === 'vertical' && styles.entryContentVertical]}>
				{entries.map(entry => <PanelItem key={entry.id} entry={entry} selected={selectedId === entry.id} vertical={panelLayout === 'vertical'} fiveAcross={mode === 'goals'} onPress={() => setSelectedId(current => current === entry.id ? undefined : entry.id)} />)}
			</View>
			{selectedEntry ? <PanelDescription entry={selectedEntry} /> : null}
			<PrimaryMetricsPanel />
		</View>
	);
}

function PanelHeading({ title, hint }: { title: string; hint: string }) {
	return (
		<View style={styles.heading}>
			<Text style={styles.headingTitle}>{title}</Text>
			<Text numberOfLines={1} adjustsFontSizeToFit style={styles.headingHint}>{hint} · tap for details</Text>
		</View>
	);
}

function PanelItem({ entry, selected, vertical = false, fiveAcross = false, onPress }: { entry: PanelEntry; selected: boolean; vertical?: boolean; fiveAcross?: boolean; onPress: () => void }) {
	return (
		<Pressable accessibilityRole="button" accessibilityLabel={`${entry.label}, ${entry.value ?? ''}`} accessibilityState={{ selected }} onPress={onPress} style={[styles.panelItem, fiveAcross && styles.panelItemFiveAcross, vertical && styles.panelItemColumn, selected && { borderBottomColor: entry.color }, selected && styles.panelItemSelected]}>
			<Text style={[styles.panelIcon, { color: entry.color }]}>{entry.icon}</Text>
			<View style={[styles.panelCopy, vertical && styles.panelCopyColumn]}>
			<Text numberOfLines={2} adjustsFontSizeToFit style={styles.panelLabel}>{entry.label}</Text>
			<Text numberOfLines={1} adjustsFontSizeToFit style={[styles.panelValue, { color: entry.color }]}>{entry.value ?? ''}</Text>
			</View>
		</Pressable>
	);
}

function PanelDescription({ entry }: { entry: PanelEntry }) {
	return (
		<View style={styles.description}>
			<Text style={[styles.descriptionTitle, { color: entry.color }]}>{entry.icon} {entry.label}</Text>
			<Text style={styles.descriptionText}>{entry.description}</Text>
		</View>
	);
}

const styles = StyleSheet.create({
	panel: { minHeight: 68, backgroundColor: colors.surfaceRaised, borderBottomColor: colors.line, borderBottomWidth: 1, paddingHorizontal: space.lg, paddingVertical: space.sm },
	heading: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', gap: space.sm, borderBottomColor: colors.line, borderBottomWidth: StyleSheet.hairlineWidth, paddingBottom: space.xs },
	headingTitle: { color: colors.ink, fontFamily: appFonts.bold, fontSize: 12, letterSpacing: 0.2 },
	headingHint: { flex: 1, color: colors.muted, fontFamily: appFonts.regular, fontSize: 9, textAlign: 'right' },
	entryContent: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'stretch', rowGap: space.xs, paddingVertical: space.xs },
	entryContentVertical: { alignItems: 'stretch' },
	panelItem: { width: '23.5%', minWidth: 0, minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 1, paddingVertical: 3, borderBottomWidth: 2, borderBottomColor: 'transparent' },
	panelItemFiveAcross: { width: '19%' },
	panelItemColumn: { flexDirection: 'column', justifyContent: 'center', alignItems: 'center', gap: 1 },
	panelItemSelected: { backgroundColor: colors.canvasRaised },
	panelIcon: { width: 18, fontSize: 16, textAlign: 'center' },
	panelCopy: { flex: 1, minWidth: 0, alignItems: 'flex-start', gap: 1 },
	panelCopyColumn: { width: '100%', alignItems: 'center' },
	panelLabel: { width: '100%', color: colors.muted, fontFamily: appFonts.medium, fontSize: 8, lineHeight: 11, letterSpacing: 0.2, textTransform: 'uppercase' },
	panelValue: { width: '100%', maxWidth: '100%', fontFamily: appFonts.bold, fontSize: 11 },
	resourceGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'stretch', rowGap: space.xs, width: '100%' },
	description: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: space.xs, paddingTop: space.sm, paddingBottom: space.xs },
	descriptionTitle: { fontFamily: appFonts.bold, fontSize: 12 },
	descriptionText: { color: colors.ink, fontFamily: appFonts.regular, fontSize: 11, lineHeight: 16, marginTop: 2 },
});
