import { spellSizeIcon } from '@/components/app-shell/spell-icons';
import { displayFuryStage } from '@/components/ui/fury-display';
import { appFonts, dragonTheme } from '@/constants/dragon-theme';
import { WORLD_CONSTANTS } from '@/constants/world.constants';
import { calculateAverageCrimsonHeartCharge, calculateFuryChange } from '@/data/calculations/formula-resources';
import { calculateProgressionPreview } from '@/data/calculations/progression-preview';
import { milestoneForEnergy, milestoneLabel } from '@/data/world-data/milestones';
import { SPELL_SIZES } from '@/data/world-data/spells';
import { useOfflineProgressStore } from '@/store/store-offline-progress/_useOfflineProgressStore';
import { useOnlineProgressStore } from '@/store/store-online-progress/_useOnlineProgressStore';
import { useProductionSpecialStore } from '@/store/store-production-special/_useProductionSpecialStore';
import { useProductivityStore } from '@/store/store-productivity/_useProductivityStore';
import { useAppStore } from '@/store/useAppStore';
import { useWorldStore } from '@/store/store-world/_useWorldStore';
import type { Goal } from '@/types/goals.types';
import type { AppActivity } from '@/types/world.types';
import { decimal, formatDecimal } from '@/utils/decimal';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useShallow } from 'zustand/react/shallow';

export type PanelMode = 'world' | 'population' | 'goals' | 'resources' | 'spells';

const { colors, space } = dragonTheme;

type ResourcePanelId = 'energy' | 'darkEnergy' | 'plasma' | 'darkPlasma' | 'anomaly' | 'chaosEnergy' | 'shards' | 'quarks';
type PanelEntry = { id: string; label: string; value?: string; icon: string; color: string; description: string };

const RESOURCE_TILES: readonly PanelEntry[] = [
	{ id: 'energy', label: 'Energy', icon: '⚡', color: colors.gold, description: 'The core production resource. Producers, amplifiers, and most clicker upgrades turn Energy into deeper progression.' },
	{ id: 'darkEnergy', label: 'Dark Energy', icon: '◈', color: colors.violet, description: 'Harvested from completed goals and generated by dark systems. Spend it on Energy Upgrades and advanced production.' },
	{ id: 'plasma', label: 'Plasma', icon: '◉', color: colors.crimsonBright, description: 'Earned by sacrificing a developed Energy run through Armageddon. Plasma powers prestige upgrades, monuments, and deities.' },
	{ id: 'darkPlasma', label: 'Dark Plasma', icon: '◌', color: colors.violet, description: 'A permanent Transcension currency used for the deepest production, monument, and prestige upgrades.' },
	{ id: 'anomaly', label: 'Anomaly', icon: '⌁', color: colors.blue, description: 'A persistent deep-progression currency earned through Transcension and spent on Titans, Deities, Forges, and respec powers.' },
	{ id: 'chaosEnergy', label: 'Chaos Energy', icon: '✦', color: colors.crimsonBright, description: 'Primordial energy produced through Titan systems. It strengthens several late-game multipliers and growth effects.' },
	{ id: 'shards', label: 'Shards', icon: '◆', color: colors.gold, description: 'Crimson Shards are a flexible meta-currency. Spend them in the Black Market, on selected unlocks, and on dragon defenses such as Anger Shields.' },
	{ id: 'quarks', label: 'Quarks', icon: '◇', color: colors.blue, description: 'Quarks fuel high-tier evolution, monument, and Convertor systems.' },
];

const FURY_RATES: Record<AppActivity, number> = {
	pomodoro: -1 / 60,
	'pomodoro-break': -0.5 / 60,
	'off-app': 0.5 / 3600,
	'allowed-app': 1 / 3600,
	idle: 1 / 3600,
	'blocked-app': 5 / 3600,
};
const activityLabel = (activity: AppActivity) => activity.replaceAll('-', ' ');
const difficultyValue = { trivial: 1, easy: 2, medium: 3, hard: 4, 'hard-plus': 5 } as const;
const baseGoalFuryLoss = (goal: Goal) => {
	const difficulty = difficultyValue[goal.difficulty];
	const late = goal.dueAt ? Date.parse(goal.completedAt ?? '') > Date.parse(goal.dueAt) : false;
	const pomodoro = goal.type === 'special-habit' && goal.specialKind.startsWith('pomodoro-');
	const daysToComplete = goal.type === 'task' ? Math.max(0, Math.floor((Date.parse(goal.completedAt ?? goal.createdAt) - Date.parse(goal.createdAt)) / 86_400_000)) : 0;
	const baseXp =
		late ? 2 + goal.subgoals.length
		: pomodoro ? 3 + goal.streak + goal.subgoals.length
		: goal.type === 'special-habit' ? 6 + 2 * goal.streak + goal.subgoals.length
		: goal.type === 'habit' ? 5 + difficulty + goal.streak + goal.subgoals.length
		: 5 + difficulty + daysToComplete + goal.subgoals.length;
	return decimal(baseXp);
};
const durationLabel = (seconds: number) => `${(seconds / 3600).toFixed(1)}h`;

export function SecondaryPanel({ mode }: { mode: PanelMode }) {
	const { resources, totalAllTime, deaths, dragon, hostiles, angerShields, getFuryBand } = useWorldStore(useShallow(state => ({ resources: state.resourceStore.resources, totalAllTime: state.resourceStore.totalAllTime, deaths: state.resourceStore.populationDead, dragon: state.resourceStore.dragon, hostiles: state.populationStore, angerShields: state.dragonStore.angerShields, getFuryBand: state.dragonStore.getFuryBand })));
	const goals = useProductivityStore(state => state.goals);
	const surveys = useProductivityStore(state => state.surveys);
	const pomodoro = useProductivityStore(state => state.pomodoro);
	const spells = useProductionSpecialStore(state => state.spells.spellInventory);
	const heart = useProductionSpecialStore(useShallow(state => ({ charge: state.crimsonHeart.charge, getTargetCharge: state.crimsonHeart.getTargetCharge, getChargeRate: state.crimsonHeart.getChargeRate })));
	const offline = useOfflineProgressStore(useShallow(state => ({ offAppSeconds: state.offAppSeconds, allowedAppSeconds: state.allowedAppSeconds, blockedAppSeconds: state.blockedAppSeconds, appBlockingMode: state.appBlockingMode })));
	const panelLayout = useAppStore(state => state.secondaryPanelLayout);
	const gameMode = useWorldStore(state => state.optionsStore.gameMode);
	const configuredActivity = useWorldStore(state => state.optionsStore.activity);
	const furyBand = getFuryBand();
	const furyStage = displayFuryStage(furyBand, angerShields);
	const milestone = milestoneForEnergy(totalAllTime.energy);
	const online = useOnlineProgressStore.getState();
	const baseProduction = online.calculateProducerEnergy(1, 1, 'idle');
	const amplification = online.calculateAmplification();
	const energyPerSecond = baseProduction.times(amplification).times(online.calculateOtherEnergyMultipliers());
	const activity: AppActivity = pomodoro.status === 'countdown-active' || pomodoro.status === 'count-up' ? 'pomodoro' : pomodoro.status === 'countdown-break' ? 'pomodoro-break' : configuredActivity;
	const activeGoalPressure = Math.max(0, goals.incompleteHabits.length - 10) + Math.max(0, goals.incompleteTasks.length - 10);
	const averageHeart = calculateAverageCrimsonHeartCharge(heart.charge, heart.getTargetCharge(activity), 3_600, heart.getChargeRate());
	const estimatedFuryPerHour = calculateFuryChange(FURY_RATES[activity], WORLD_CONSTANTS.gameModes.furyMultiplier[gameMode], 3_600, activeGoalPressure, 1).times(Math.max(1, averageHeart));
	const progression = calculateProgressionPreview(heart.charge);
	const pendingGoals = [...goals.completed, ...goals.specialHabits.filter(goal => goal.status === 'completed')].filter(goal => goals.pendingHarvestIds.includes(goal.id));
	const projectedGoalFuryLoss = pendingGoals.reduce((total, goal) => total.plus(baseGoalFuryLoss(goal)), decimal(0));
	const offlineSeconds = offline.offAppSeconds + offline.allowedAppSeconds + offline.blockedAppSeconds;
	const offlineDescription = `Offline time uses the same closed-form ticking engine as live time. Stored now: Off phone ${durationLabel(offline.offAppSeconds)}, Allowed apps ${durationLabel(offline.allowedAppSeconds)}, Blocked apps ${durationLabel(offline.blockedAppSeconds)}. Base Fury rates are +0.5/hour off phone, +1/hour for allowed apps, and +5/hour while blocked before Heart, mode, goals, spells, and shields.`;
	const goalFuryDescription = pendingGoals.length ? `Projected base Fury loss from ${pendingGoals.length} pending harvest${pendingGoals.length === 1 ? '' : 's'}: ${formatDecimal(projectedGoalFuryLoss)}. Final loss is modified by difficulty, streaks, challenges, Aphrodite, premium effects, and calm spells at harvest.` : 'Goals reduce Fury when their rewards are harvested, not merely when they are completed. Complete and harvest goals to receive their Fury-loss reward.';
	const [selectedId, setSelectedId] = useState<string>();

	if (mode === 'resources') {
		const visibleTiles = RESOURCE_TILES.filter(tile => totalAllTime[tile.id as ResourcePanelId].gt(0));
		const selectedTile = visibleTiles.find(tile => tile.id === selectedId);
		return (
			<View style={styles.panel}>
				<View style={styles.resourceGrid}>
					{visibleTiles.map(tile => (
						<PanelItem
							key={tile.id}
							entry={{ ...tile, value: `${formatDecimal(resources[tile.id as ResourcePanelId])}${tile.id === 'energy' ? ` · ${formatDecimal(energyPerSecond)} /s` : ''}` }}
							vertical={panelLayout === 'vertical'}
							selected={selectedId === tile.id}
							onPress={() => setSelectedId(current => current === tile.id ? undefined : tile.id)}
						/>
					))}
				</View>
				{selectedTile ? <PanelDescription entry={selectedTile} /> : null}
			</View>
		);
	}

	const entries = mode === 'goals' ?
		[
			{ id: 'habits', label: 'Habits', value: `${goals.incompleteHabits.length}`, icon: '✓', color: colors.gold, description: 'Repeatable goals that build a streak when completed on their schedule.' },
			{ id: 'tasks', label: 'Tasks', value: `${goals.incompleteTasks.length}`, icon: '▤', color: colors.blue, description: 'One-time goals that can be completed and harvested for progression rewards.' },
			{ id: 'special', label: 'Dragon Rituals', value: `${goals.specialHabits.filter(goal => goal.status === 'incomplete').length}`, icon: '✦', color: colors.crimsonBright, description: 'Permanent survey and Pomodoro goals. They are checked off automatically by their linked activity.' },
			{ id: 'check-in-streak', label: 'Check-In streak', value: `${surveys.checkInStreak}`, icon: '✓', color: colors.gold, description: 'Consecutive daily check-in cycles completed.' },
			{ id: 'check-out-streak', label: 'Check-Out streak', value: `${surveys.checkOutStreak}`, icon: '⟲', color: colors.violet, description: 'Consecutive daily check-out cycles completed.' },
		]
	: mode === 'spells' ?
		[
			{ id: 'backpack', label: 'Backpack', value: `${spells.length}`, icon: '✧', color: colors.gold, description: 'Your current spell inventory. Open the backpack in the Effects panel to inspect or activate spells.' },
			...SPELL_SIZES.map(size => ({ id: `spell-${size.size}`, label: size.name, value: `${spells.filter(spell => spell.size === size.size).length}`, icon: spellSizeIcon(size.size), color: colors.violet, description: `${size.name} spells have a ×${size.multiplier} base effect and can be combined through the Convertor when their recipe allows it.` })),
		]
	: mode === 'population' ?
		[
			{ id: 'population', label: 'Population', value: formatDecimal(resources.population), icon: '◎', color: colors.blue, description: 'The living population of Earth. Population growth stops during blocked activity, Lock-In, dragon death, or a paused world state.' },
			{ id: 'population-growth', label: 'Growth', value: `+${formatDecimal(progression.populationPerTick)} / tick`, icon: '↗', color: colors.green, description: `Current Population gained per Heart tick: ${formatDecimal(progression.populationPerTick)}. Heart ticks are ${formatDecimal(progression.heartTicksPerSecond, 3)} per second; Angry and Critical Fury can stop growth or cause population loss.` },
			{ id: 'threats', label: 'Threats', value: `${formatDecimal(hostiles.zombies)} · ${formatDecimal(hostiles.cyborgs)}`, icon: '☣', color: colors.crimsonBright, description: 'Zombies and cyborgs are population threats. Their growth and effects change with Fury stages and world modifiers.' },
			{ id: 'deaths', label: 'Deaths', value: formatDecimal(deaths), icon: '†', color: colors.muted, description: 'The total population lost to threats and Fury effects during this run.' },
		]
	: [
			{ id: 'milestone', label: 'Milestone', value: milestoneLabel(milestone), icon: '◆', color: colors.gold, description: 'Milestones are based on all-time Energy and unlock new chambers, systems, and rewards.' },
			{ id: 'fury', label: 'Fury', value: `${furyStage} · ${formatDecimal(resources.fury)} / ${formatDecimal(dragon.furyThreshold)}`, icon: '🔥', color: colors.crimsonBright, description: `Dragon's Fury / Anger Level (Milestone 1). Current stage: ${furyStage}. Fury rises when goals are missed or the app is neglected. Shields make the stage Calm, protect against Angry or higher, absorb Fury temporarily, gain at ×½ in Calm, and cap at the threshold of ${formatDecimal(dragon.furyThreshold)}. Without shields: 0–threshold is Normal, threshold–2× is Angry, and 2×–3× is Critical; exceeding the cap triggers Supernova mass destruction. Angry stops Population growth with 1× losses per tick; Critical causes 2×. Estimated ${estimatedFuryPerHour.gte(0) ? '+' : ''}${formatDecimal(estimatedFuryPerHour)} Fury/hour during ${activityLabel(activity)}. Hard and Hard+ raise Fury gain and its cap for more Energy; Invincible and Lock-In pause Fury. Eros can reduce Fury through the Convertor. ${goalFuryDescription}` },
			{ id: 'streak', label: 'Streak', value: `${surveys.checkInStreak} · ${surveys.checkOutStreak}`, icon: '⟲', color: colors.gold, description: `Survey streaks: ${surveys.checkInStreak} check-in and ${surveys.checkOutStreak} check-out. Complete the daily survey cycle to keep both streaks moving.` },
			{ id: 'important', label: 'Important Info', value: `${dragon.ageDays.toFixed(1)}d · ${durationLabel(offlineSeconds)}`, icon: 'ⓘ', color: colors.violet, description: `Dragon age is ${dragon.ageDays.toFixed(1)} days and the current activity is ${activityLabel(activity)}. Offline ticking stored so far: ${offlineDescription} ${goalFuryDescription}` },
	];
	const selectedEntry = entries.find(entry => entry.id === selectedId);

	return (
		<View style={styles.panel}>
			<View style={[styles.entryContent, panelLayout === 'vertical' && styles.entryContentVertical]}>
				{entries.map(entry => <PanelItem key={entry.id} entry={entry} selected={selectedId === entry.id} vertical={panelLayout === 'vertical'} onPress={() => setSelectedId(current => current === entry.id ? undefined : entry.id)} />)}
			</View>
			{selectedEntry ? <PanelDescription entry={selectedEntry} /> : null}
		</View>
	);
}

function PanelItem({ entry, selected, vertical = false, onPress }: { entry: PanelEntry; selected: boolean; vertical?: boolean; onPress: () => void }) {
	return (
		<Pressable accessibilityRole="button" accessibilityLabel={`${entry.label}, ${entry.value ?? ''}`} accessibilityState={{ selected }} onPress={onPress} style={[styles.panelItem, vertical && styles.panelItemColumn, selected && { borderBottomColor: entry.color }, selected && styles.panelItemSelected]}>
			<Text style={[styles.panelIcon, { color: entry.color }]}>{entry.icon}</Text>
			<View style={[styles.panelCopy, vertical && styles.panelCopyColumn]}>
			<Text numberOfLines={2} adjustsFontSizeToFit style={styles.panelLabel}>{entry.label}</Text>
			<Text numberOfLines={1} adjustsFontSizeToFit style={[styles.panelValue, { color: entry.color }]}>{entry.value ?? ''}</Text>
			</View>
		</Pressable>
	);
}

function PanelDescription({ entry }: { entry: PanelEntry }) {
	return (
		<View style={styles.description}>
			<Text style={[styles.descriptionTitle, { color: entry.color }]}>{entry.icon} {entry.label}</Text>
			<Text style={styles.descriptionText}>{entry.description}</Text>
		</View>
	);
}

const styles = StyleSheet.create({
	panel: { minHeight: 68, backgroundColor: colors.surfaceRaised, borderBottomColor: colors.line, borderBottomWidth: 1, paddingHorizontal: space.lg, paddingVertical: space.sm },
	entryContent: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'stretch', rowGap: space.xs, paddingVertical: space.xs },
	entryContentVertical: { alignItems: 'stretch' },
	panelItem: { width: '31%', minWidth: 0, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 2, paddingVertical: 4, borderBottomWidth: 2, borderBottomColor: 'transparent' },
	panelItemColumn: { flexDirection: 'column', justifyContent: 'center', alignItems: 'center', gap: 1 },
	panelItemSelected: { backgroundColor: colors.canvasRaised },
	panelIcon: { width: 18, fontSize: 16, textAlign: 'center' },
	panelCopy: { flex: 1, minWidth: 0, alignItems: 'flex-start', gap: 1 },
	panelCopyColumn: { width: '100%', alignItems: 'center' },
	panelLabel: { width: '100%', color: colors.muted, fontFamily: appFonts.medium, fontSize: 8, lineHeight: 11, letterSpacing: 0.2, textTransform: 'uppercase' },
	panelValue: { width: '100%', maxWidth: '100%', fontFamily: appFonts.bold, fontSize: 11 },
	resourceGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'stretch', rowGap: space.xs, width: '100%' },
	description: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: space.xs, paddingTop: space.sm, paddingBottom: space.xs },
	descriptionTitle: { fontFamily: appFonts.bold, fontSize: 12 },
	descriptionText: { color: colors.ink, fontFamily: appFonts.regular, fontSize: 11, lineHeight: 16, marginTop: 2 },
});
