/** Route-specific presentation for the Lair route. */
import { appFonts, dragonTheme } from '@/constants/dragon-theme';
import { StyleSheet } from 'react-native';

const { colors, radius, space } = dragonTheme;

export const styles = StyleSheet.create({
	metricLabel: { color: colors.muted, fontFamily: appFonts.medium, fontSize: 10, textTransform: 'uppercase', letterSpacing: 1 },
	energyHero: { alignItems: 'center' },
	energy: { color: colors.gold, fontFamily: appFonts.black, fontSize: 36 },
	dragonStage: { minHeight: 310, alignItems: 'center', justifyContent: 'center' },
	dragonHalo: { position: 'absolute', width: 230, height: 230, borderRadius: 120, backgroundColor: colors.crimsonSoft, opacity: 0.65 },
	dragonWrap: { width: '100%', height: 220 },
	dragon: { width: '100%', height: '100%' },
	dragonGlyph: { color: colors.gold, fontFamily: appFonts.black, fontSize: 140, textAlign: 'center', lineHeight: 210 },
	clickFeedback: { position: 'absolute', width: 220, color: colors.gold, fontFamily: appFonts.bold, fontSize: 14, textAlign: 'center' },
	dragonName: { color: colors.ink, fontFamily: appFonts.black, fontSize: 23 },
	dragonMeta: { color: colors.muted, fontFamily: appFonts.medium, fontSize: 11, textTransform: 'capitalize' },
	itemList: { gap: space.sm },
	itemCard: { padding: space.md },
	blueprintCard: { paddingHorizontal: space.md, paddingVertical: space.sm, gap: space.sm },
	blueprintHeader: { flexDirection: 'row', alignItems: 'center', gap: space.sm },
	blueprintIcon: { color: colors.gold, fontSize: 18 },
	blueprintCopy: { flex: 1, gap: 1 },
	blueprintRequirement: { gap: 3 },
	blueprintRequirementRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: space.sm },
	blueprintRequirementLabel: { flex: 1, color: colors.muted, fontFamily: appFonts.regular, fontSize: 10, lineHeight: 14 },
	blueprintRequirementProgress: { color: colors.gold, fontFamily: appFonts.medium, fontSize: 10 },
	itemRow: { flexDirection: 'row', gap: space.md, alignItems: 'center' },
	itemRowReversed: { flexDirection: 'row-reverse' },
	itemIcon: { width: 48, height: 48, borderRadius: radius.medium, backgroundColor: colors.canvas, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
	itemIconText: { color: colors.gold, fontSize: 22 },
	itemCopy: { flex: 1, minWidth: 0, gap: 2 },
	itemLevel: { color: colors.crimsonBright, fontFamily: appFonts.bold, fontSize: 9, letterSpacing: 1 },
	itemName: { color: colors.ink, fontFamily: appFonts.semibold, fontSize: 14, textTransform: 'capitalize' },
	metric: { color: colors.blue, fontFamily: appFonts.semibold, fontSize: 11, maxWidth: '100%' },
	cost: { color: colors.gold, fontFamily: appFonts.medium, fontSize: 11, maxWidth: '100%' },
	itemActions: { gap: 6, alignItems: 'stretch', flexShrink: 1, maxWidth: 132 },
	maxedText: { color: colors.green, fontFamily: appFonts.black, fontSize: 11, letterSpacing: 1, textAlign: 'center' },
	goalMultiplierHeader: { flexDirection: 'row', alignItems: 'center', gap: space.md },
	goalMultiplierLevel: { width: 64, minHeight: 64, borderRadius: radius.medium, backgroundColor: colors.canvas, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', gap: 2 },
	goalMultiplierLevelNumber: { color: colors.gold, fontFamily: appFonts.black, fontSize: 24 },
	heartStatsRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: space.md },
	heartStage: { minHeight: 210, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
	heartGlyph: { color: colors.crimsonBright, fontSize: 132, lineHeight: 160, textShadowColor: colors.crimson, textShadowRadius: 24 },
	heartQuote: { position: 'absolute', width: 280, color: colors.gold, fontFamily: appFonts.semibold, fontSize: 12, lineHeight: 18, textAlign: 'center' },
	heartNumber: { color: colors.crimsonBright, fontFamily: appFonts.black, fontSize: 30, textAlign: 'center' },
	heartChargeDetail: { color: colors.muted, fontFamily: appFonts.medium, fontSize: 11, textAlign: 'center' },
	heartWarning: { width: '100%', marginTop: space.md, padding: space.sm, backgroundColor: colors.crimsonSoft, borderColor: colors.crimsonBright, borderWidth: 1, borderRadius: radius.medium, alignItems: 'center', gap: 2 },
	heartWarningTitle: { color: colors.crimsonBright, fontFamily: appFonts.bold, fontSize: 12, textAlign: 'center' },
	heartWarningText: { color: colors.ink, fontFamily: appFonts.medium, fontSize: 11, textAlign: 'center' },
	generationStats: { width: '100%', flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', gap: space.xl, marginTop: space.md },
	generationStat: { minWidth: 120, alignItems: 'center', gap: 2 },
	generationLabel: { color: colors.muted, fontFamily: appFonts.medium, fontSize: 10, textTransform: 'uppercase', letterSpacing: 0.7, textAlign: 'center' },
	generationValue: { color: colors.gold, fontFamily: appFonts.bold, fontSize: 17, textAlign: 'center' },
	ability: { minHeight: 52, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: space.md, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: space.sm },
	converterInputRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: space.sm },
	converterInput: { minWidth: 90, flex: 1, minHeight: 42, borderRadius: radius.medium, backgroundColor: colors.canvas, borderColor: colors.line, borderWidth: 1, color: colors.ink, fontFamily: appFonts.mono, paddingHorizontal: 12 },
	prestigeNumber: { color: colors.gold, fontFamily: appFonts.black, fontSize: 31 },
	resourceBalanceCard: { paddingHorizontal: space.md, paddingVertical: space.sm },
	resourceBalanceRow: { flexDirection: 'row', alignItems: 'center', gap: space.sm },
	resourceBalanceIcon: { color: colors.violet, fontSize: 24 },
	resourceBalanceCopy: { flex: 1, gap: 1 },
	resourceBalanceAmount: { color: colors.violet, fontFamily: appFonts.black, fontSize: 22 },
	resourceBalanceLabel: { color: colors.muted, fontFamily: appFonts.medium, fontSize: 10, textTransform: 'uppercase', letterSpacing: 0.8 },
	monument: { flexDirection: 'row', gap: space.md, alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.line, paddingTop: space.md },
});
