/** Shared world rules so balancing values do not leak into stores or UI. */
export const WORLD_CONSTANTS = {
	secondsPerDay: 86_400,
	initialPopulation: 8_000_000_000,
	resourceTickSeconds: 1,
	crimsonHeartRatePerSecond: 1,
	crimsonHeartDischargeRatePerSecond: 0.25,
	clickRest: {
		minimumClicks: 100,
		maximumClicks: 200,
		recoveryTicks: 1_000,
		minimumTicksPerSecond: 1,
	},
	armageddonDarkEnergyBase: 500,
	transcensionDarkEnergyBase: 25_000,
	titanomachyProductionAdditivePerAge: 0.02,
	population: {
		damping: 0.01,
		// Soft ceiling, not a hard cap: growth continues at r_min above this value.
		softCeiling: '1e12',
		maximumGrowthRate: 0.001,
		minimumGrowthRate: 0.00001,
		normalDecline: 0.5,
		angryDecline: 1.1,
		criticalDecline: 1.3,
		zombieGrowth: { calm: 0.35, normal: 0.35, angry: 0.65, critical: 1, supernova: 1 },
		cyborgGrowth: { calm: 0.3, normal: 0.3, angry: 0.6, critical: 0.95, supernova: 0.95 },
		zombieOverpopulationDecline: 0.5,
		zombieExtinctionDecline: 1.5,
	},
	dragon: {
		defaultName: 'Unnamed Dragon',
		baseFuryThreshold: 100,
		furyDeathMultiplier: 3,
		angerShieldGainFromExcessCalm: 0.5,
		reviveGraceSeconds: 30 * 60,
		revivePopulationMultiplier: 10,
		supernovaPopulationLoss: 0.5,
		supernovaProducerLoss: 0.5,
		offlineSpellIntervalSeconds: 7 * 86_400,
	},
	gameModes: {
		energyMultiplier: { invincible: 0.5, 'lock-in': 0, easy: 1, medium: 2, hard: 4, 'hard-plus': 6 },
		furyMultiplier: { invincible: 0, 'lock-in': 0, easy: 1, medium: 2, hard: 4, 'hard-plus': 6 },
		maxFuryMultiplier: { invincible: 1, 'lock-in': 1, easy: 1, medium: 2, hard: 4, 'hard-plus': 6 },
	},
	dragonStages: [
		{ id: 'egg', minimumAgeDays: 0, label: 'Egg' },
		{ id: 'hatchling', minimumAgeDays: 10, label: 'Hatchling' },
		{ id: 'dragonet', minimumAgeDays: 20, label: 'Dragonet' },
		{ id: 'juvenile', minimumAgeDays: 30, label: 'Juvenile' },
		{ id: 'young-adult', minimumAgeDays: 60, label: 'Young Adult' },
		{ id: 'grown-adult', minimumAgeDays: 90, label: 'Grown Adult' },
		{ id: 'apex-adult', minimumAgeDays: 135, label: 'Apex Adult' },
		{ id: 'elder-dragon', minimumAgeDays: 180, label: 'Elder Dragon' },
		{ id: 'sovereign-dragon', minimumAgeDays: 270, label: 'Sovereign Dragon' },
		{ id: 'great-wyrm', minimumAgeDays: 365, label: 'Great Wyrm' },
		{ id: 'heart-of-chaos', minimumAgeDays: 545, label: 'Heart of Chaos' },
		{ id: 'absolute-chaos-overlord', minimumAgeDays: 730, label: 'Absolute Chaos Overlord' },
	],
} as const;
